name: GitHub Page

on:
    push:
        branches:
            - gh-pages # master æ›´æ–°è§¦å‘

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true # clone submodules
                  fetch-depth: 0 # å…‹éš†æ‰€æœ‰å†å²ä¿¡æ¯

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "0.111.3" # Hugo ç‰ˆæœ¬
                  extended: true # hugoæ’ä»¶ç‰ˆ Stackä¸»é¢˜ å¿…é¡»å¯ç”¨

            - name: Cache resources # ç¼“å­˜ resource æ–‡ä»¶åŠ å¿«ç”Ÿæˆé€Ÿåº¦
              uses: actions/cache@v2
              with:
                  path: resources
                  # æ£€æŸ¥ç…§ç‰‡æ–‡ä»¶å˜åŒ–
                  key: ${{ runner.os }}-hugocache-${{ hashFiles('content/**/*') }}
                  restore-keys: ${{ runner.os }}-hugocache-

            - name: Build # ç”Ÿæˆç½‘é¡µ åˆ é™¤æ— ç”¨ resource æ–‡ä»¶ å‰Šå‡ç©ºè¡Œ
              run: hugo --minify --gc

            - name: Deploy # éƒ¨ç½²åˆ° GitHub Page
              uses: peaceiris/actions-gh-pages@v3
              with:
                  # å¦‚æœåœ¨åŒä¸€ä¸ªä»“åº“ä¸‹ä½¿ç”¨è¯·ä½¿ç”¨ github_token å¹¶æ³¨é‡Š deploy_key
                  # github_token: ${{ secrets.GITHUB_TOKEN }}
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

                  # å¦‚æœåœ¨åŒä¸€ä¸ªä»“åº“è¯·æ³¨é‡Š
                  external_repository: Tauzi/myblog # ä½ çš„ GitHub page ä»“åº“ example/example.github.io

                  publish_dir: ./public
                  user_name: "github-actions[bot]"
                  user_email: "github-actions[bot]@users.noreply.github.com"
                  full_commit_message: Deploy from ${{ github.repository }}@${{ github.sha }} ğŸš€
                
